services:
  web:
    image: ${APP_IMAGE:-ghcr.io/pranavnbapat/nbs_readapt:latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nbs_readapt_web
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-9500}:8000"
    depends_on:
      postgres:
        condition: service_healthy
      opensearch:
        condition: service_started

  postgres:
    image: postgres:16
    container_name: nbs_readapt_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PUBLIC_PORT:-9501}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:9.5
    container_name: nbs_readapt_pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-9502}:80"
    depends_on:
      postgres:
        condition: service_healthy

  opensearch:
    image: opensearchproject/opensearch:3.5.0
    container_name: nbs_readapt_opensearch
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${OPENSEARCH_PUBLIC_PORT:-9503}:9200"
      - "${OPENSEARCH_METRICS_PUBLIC_PORT:-9504}:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

volumes:
  postgres_data:
  opensearch_data:
