services:
  traefik:
    image: traefik:v3.6.6
    container_name: nbs_readapt_traefik
    restart: unless-stopped
    env_file:
      - .env
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
      - ./acme.json:/letsencrypt/acme.json
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.rule=Host(`${TRAEFIK_DASHBOARD_HOST:-traefik-nbs-readapt.nexavion.com}`)
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.routers.traefik-dashboard.middlewares=dashboard-auth
      - traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS:-admin:$$apr1$$9FtIXSEo$$OzKz6xbUwSGaD3vg0DZFJ0}

networks:
  proxy:
    name: nbs_readapt_proxy
