from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("country_code", models.CharField(blank=True, max_length=8)),
            ],
            options={"ordering": ["name"], "verbose_name_plural": "countries"},
        ),
        migrations.CreateModel(
            name="Hazard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_label", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("records_imported", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="NbsType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={"ordering": ["name"], "verbose_name": "NbS type", "verbose_name_plural": "NbS types"},
        ),
        migrations.CreateModel(
            name="RepositoryRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_dataset", models.CharField(choices=[("papers", "Papers"), ("network_projects", "Network Projects"), ("eu_projects", "EU Funded Projects"), ("policies", "Policies")], max_length=32)),
                ("source_sheet", models.CharField(blank=True, max_length=255)),
                ("source_record_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=1024)),
                ("source_database", models.CharField(blank=True, max_length=255)),
                ("record_subtype", models.CharField(blank=True, max_length=255)),
                ("document_type", models.CharField(blank=True, max_length=255)),
                ("policy_level", models.CharField(blank=True, max_length=255)),
                ("geographic_scope", models.CharField(blank=True, max_length=255)),
                ("territorial_context", models.CharField(blank=True, max_length=255)),
                ("environment_type", models.CharField(blank=True, max_length=255)),
                ("implementation_stage", models.CharField(blank=True, max_length=255)),
                ("community_engagement_level", models.CharField(blank=True, max_length=255)),
                ("data_availability", models.CharField(blank=True, max_length=255)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("start_year", models.IntegerField(blank=True, null=True)),
                ("end_year", models.IntegerField(blank=True, null=True)),
                ("lead_organization", models.CharField(blank=True, max_length=512)),
                ("authors", models.TextField(blank=True)),
                ("affiliations", models.TextField(blank=True)),
                ("acronym", models.CharField(blank=True, max_length=255)),
                ("funding_source", models.CharField(blank=True, max_length=255)),
                ("funding_contribution", models.CharField(blank=True, max_length=255)),
                ("doi", models.CharField(blank=True, max_length=512)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("source_url_secondary", models.URLField(blank=True, max_length=1000)),
                ("abstract", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("objective", models.TextField(blank=True)),
                ("methods", models.TextField(blank=True)),
                ("outcomes_targeted", models.TextField(blank=True)),
                ("ecological_impacts", models.TextField(blank=True)),
                ("socio_economic_impacts", models.TextField(blank=True)),
                ("governance_insights", models.TextField(blank=True)),
                ("finance_insights", models.TextField(blank=True)),
                ("implementation_steps", models.TextField(blank=True)),
                ("monitoring_reporting", models.TextField(blank=True)),
                ("barriers", models.TextField(blank=True)),
                ("enablers", models.TextField(blank=True)),
                ("lessons", models.TextField(blank=True)),
                ("key_findings", models.TextField(blank=True)),
                ("enforcement_mechanisms", models.TextField(blank=True)),
                ("nbs_relevance", models.TextField(blank=True)),
                ("nbs_commitment", models.TextField(blank=True)),
                ("country_display", models.TextField(blank=True)),
                ("city_location", models.TextField(blank=True)),
                ("location_text", models.TextField(blank=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("normalized_payload", models.JSONField(blank=True, default=dict)),
                ("countries", models.ManyToManyField(blank=True, related_name="records", to="repository.country")),
                ("import_batch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="records", to="repository.importbatch")),
                ("primary_hazards", models.ManyToManyField(blank=True, related_name="primary_records", to="repository.hazard")),
                ("primary_nbs_types", models.ManyToManyField(blank=True, related_name="primary_records", to="repository.nbstype")),
                ("secondary_hazards", models.ManyToManyField(blank=True, related_name="secondary_records", to="repository.hazard")),
                ("secondary_nbs_types", models.ManyToManyField(blank=True, related_name="secondary_records", to="repository.nbstype")),
            ],
            options={"ordering": ["source_dataset", "title"]},
        ),
        migrations.AddConstraint(
            model_name="repositoryrecord",
            constraint=models.UniqueConstraint(fields=("source_dataset", "source_record_id"), name="uniq_repository_record_source_id"),
        ),
    ]
